### ISSUE TITLE
pkg-cacher fails with Perl 5.18

### ISSUE THREAD

**Issue by ganto** [open-sw/pkg-cacher#29]
Hi

I built and tried to run pkg-cacher on Debian Jessie which is using Perl 5.18.2. Unfortunately it fails with the following error:

```
Experimental "our" subs not enabled at /usr/share/pkg-cacher/pkg-cacher line 268.
```
After a bit of googling, I [found](http://www.perlmonks.org/?node_id=1035295) that this seems a common issue for code running on Perl 5.18. If I add the following lines to the file, pkg-cacher will work again:

```perl
use feature 'lexical_subs';
no warnings 'experimental::lexical_subs';
```
I'm not at all familiar with perl so I don't know what the implications of this change are. Could you please have a look at this?

Cheers and thanks for this cool application :+1: 
ganto

**Comment by Robert-Nelson** [comment]
Fixed
